const MAP2 = {
baseHeight: 2,
baseType: "rock",
map: [
  [
    new Tile({y:0, x:0, height: 2}),
    new Tile({y:0, x:1, height: 2}),
    new Tile({y:0, x:2, height: 2}),
    new Tile({y:0, x:3, height: 2}),
    new Tile({y:0, x:4, height: 2}),
    new Tile({y:0, x:5, height: 2}),
    new Tile({y:0, x:6, height: 2}),
    new Tile({y:0, x:7, height: 2}),
    new Tile({y:0, x:8, height: 2}),
    new Tile({y:0, x:9, height: 2}),
    new Tile({y:0, x:10, height: 2}),
    new Tile({y:0, x:11, height: 2}),
    new Tile({y:0, x:12, height: 2}),
    new Tile({y:0, x:13, height: 2}),
    new Tile({y:0, x:14, height: 2}),
    new Tile({y:0, x:15, height: 2}),
    new Tile({y:0, x:16, height: 2}),
    new Tile({y:0, x:17, height: 2}),
    new Tile({y:0, x:18, height: 2}),
    new Tile({y:0, x:19, height: 2})
  ],
  [
    new Tile({y:1, x:0, height: 2}),
    new Tile({y:1, x:1, height: 2}),
    new Tile({y:1, x:2, height: 2}),
    new Tile({y:1, x:3, height: 2}),
    new Tile({y:1, x:4, height: 2}),
    new Tile({y:1, x:5, height: 2}),
    new Tile({y:1, x:6, height: 2}),
    new Tile({y:1, x:7, height: 2}),
    new Tile({y:1, x:8, height: 2}),
    new Tile({y:1, x:9, height: 2}),
    new Tile({y:1, x:10, height: 2}),
    new Tile({y:1, x:11, height: 2}),
    new Tile({y:1, x:12, height: 2}),
    new Tile({y:1, x:13, height: 2}),
    new Tile({y:1, x:14, height: 2}),
    new Tile({y:1, x:15, height: 2}),
    new Tile({y:1, x:16, height: 2}),
    new Tile({y:1, x:17, height: 2}),
    new Tile({y:1, x:18, height: 2}),
    new Tile({y:1, x:19, height: 2})
  ],
  [
    new Tile({y:2, x:0, height: 2}),
    new Tile({y:2, x:1, height: 2}),
    new Tile({y:2, x:2, height: 2}),
    new Tile({y:2, x:3, height: 2}),
    new Tile({y:2, x:4, height: 2}),
    new Tile({y:2, x:5, height: 2}),
    new Tile({y:2, x:6, height: 2}),
    new Tile({y:2, x:7, height: 2}),
    new Tile({y:2, x:8, height: 2}),
    new Tile({y:2, x:9, height: 1}),
    new Tile({y:2, x:10, height: 2}),
    new Tile({y:2, x:11, height: 2}),
    new Tile({y:2, x:12, height: 2}),
    new Tile({y:2, x:13, height: 2}),
    new Tile({y:2, x:14, height: 2}),
    new Tile({y:2, x:15, height: 2}),
    new Tile({y:2, x:16, height: 2}),
    new Tile({y:2, x:17, height: 2}),
    new Tile({y:2, x:18, height: 2}),
    new Tile({y:2, x:19, height: 2})
  ],[
    new Tile({y:3, x:0, height: 2}),
    new Tile({y:3, x:1, height: 2}),
    new Tile({y:3, x:2, height: 2}),
    new Tile({y:3, x:3, height: 2}),
    new Tile({y:3, x:4, height: 2}),
    new Tile({y:3, x:5, height: 2}),
    new Tile({y:3, x:6, height: 2}),
    new Tile({y:3, x:7, height: 1}),
    new Tile({y:3, x:8, height: 1}),
    new Tile({y:3, x:9, height: 0, type: "water"}),
    new Tile({y:3, x:10, height: 0, type: "water"}),
    new Tile({y:3, x:11, height: 1}),
    new Tile({y:3, x:12, height: 2}),
    new Tile({y:3, x:13, height: 2}),
    new Tile({y:3, x:14, height: 2}),
    new Tile({y:3, x:15, height: 2}),
    new Tile({y:3, x:16, height: 2}),
    new Tile({y:3, x:17, height: 2}),
    new Tile({y:3, x:18, height: 2}),
    new Tile({y:3, x:19, height: 2})
  ],[
    new Tile({y:4, x:0, height: 2}),
    new Tile({y:4, x:1, height: 2}),
    new Tile({y:4, x:2, height: 2}),
    new Tile({y:4, x:3, height: 2}),
    new Tile({y:4, x:4, height: 2}),
    new Tile({y:4, x:5, height: 2}),
    new Tile({y:4, x:6, height: 2}),
    new Tile({y:4, x:7, height: 1}),
    new Tile({y:4, x:8, height: 0, type: "water"}),
    new Tile({y:4, x:9, height: 0, type: "water"}),
    new Tile({y:4, x:10, height: 0, type: "water"}),
    new Tile({y:4, x:11, height: 1}),
    new Tile({y:4, x:12, height: 1}),
    new Tile({y:4, x:13, height: 1}),
    new Tile({y:4, x:14, height: 2}),
    new Tile({y:4, x:15, height: 2}),
    new Tile({y:4, x:16, height: 2}),
    new Tile({y:4, x:17, height: 2}),
    new Tile({y:4, x:18, height: 2}),
    new Tile({y:4, x:19, height: 2})
  ],[
    new Tile({y:5, x:0, height: 2}),
    new Tile({y:5, x:1, height: 2}),
    new Tile({y:5, x:2, height: 2}),
    new Tile({y:5, x:3, height: 2}),
    new Tile({y:5, x:4, height: 2}),
    new Tile({y:5, x:5, height: 1}),
    new Tile({y:5, x:6, height: 0, type: "water"}),
    new Tile({y:5, x:7, height: 0, type: "water"}),
    new Tile({y:5, x:8, height: 0, type: "water"}),
    new Tile({y:5, x:9, height: 0, type: "water"}),
    new Tile({y:5, x:10, height: 0, type: "water"}),
    new Tile({y:5, x:11, height: 0, type: "water"}),
    new Tile({y:5, x:12, height: 0, type: "water"}),
    new Tile({y:5, x:13, height: 1}),
    new Tile({y:5, x:14, height: 2}),
    new Tile({y:5, x:15, height: 2}),
    new Tile({y:5, x:16, height: 2}),
    new Tile({y:5, x:17, height: 2}),
    new Tile({y:5, x:18, height: 2}),
    new Tile({y:5, x:19, height: 2})
  ],[
    new Tile({y:6,x :0, height: 2}),
    new Tile({y:6,x :1, height: 2}),
    new Tile({y:6,x :2, height: 2}),
    new Tile({y:6,x :3, height: 2}),
    new Tile({y:6,x :4, height: 2}),
    new Tile({y:6,x :5, height: 1}),
    new Tile({y:6,x :6, height: 0, type: "water"}),
    new Tile({y:6,x :7, height: 0, type: "water"}),
    new Tile({y:6,x :8, height: 0, type: "water"}),
    new Tile({y:6,x :9, height: 0, type: "water"}),
    new Tile({y:6, x:10, height: 0, type: "water"}),
    new Tile({y:6, x:11, height: 0, type: "water"}),
    new Tile({y:6, x:12, height: 0, type: "water"}),
    new Tile({y:6, x:13, height: 1}),
    new Tile({y:6, x:14, height: 1}),
    new Tile({y:6, x:15, height: 1}),
    new Tile({y:6, x:16, height: 2}),
    new Tile({y:6, x:17, height: 2}),
    new Tile({y:6, x:18, height: 2}),
    new Tile({y:6, x:19, height: 2})
  ],[
    new Tile({y:7, x:0, height: 2}),
    new Tile({y:7, x:1, height: 2}),
    new Tile({y:7, x:2, height: 2}),
    new Tile({y:7, x:3, height: 2}),
    new Tile({y:7, x:4, height: 1}),
    new Tile({y:7, x:5, height: 0, type: "water"}),
    new Tile({y:7, x:6, height: 0, type: "water"}),
    new Tile({y:7, x:7, height: 0, type: "water"}),
    new Tile({y:7, x:8, height: 0, type: "water"}),
    new Tile({y:7, x:9, height: 0, type: "water"}),
    new Tile({y:7, x:10, height: 0, type: "water"}),
    new Tile({y:7, x:11, height: 0, type: "water"}),
    new Tile({y:7, x:12, height: 0, type: "water"}),
    new Tile({y:7, x:13, height: 0, type: "water"}),
    new Tile({y:7, x:14, height: 0, type: "water"}),
    new Tile({y:7, x:15, height: 1}),
    new Tile({y:7, x:16, height: 2}),
    new Tile({y:7, x:17, height: 2}),
    new Tile({y:7, x:18, height: 2}),
    new Tile({y:7, x:19, height: 2})
  ],[
    new Tile({y:8, x:0, height: 2}),
    new Tile({y:8, x:1, height: 2}),
    new Tile({y:8, x:2, height: 2}),
    new Tile({y:8, x:3, height: 2}),
    new Tile({y:8, x:4, height: 1}),
    new Tile({y:8, x:5, height: 0, type: "water"}),
    new Tile({y:8, x:6, height: 0, type: "water"}),
    new Tile({y:8, x:7, height: 0, type: "water"}),
    new Tile({y:8, x:8, height: 0, type: "water"}),
    new Tile({y:8, x:9, height: 0, type: "water"}),
    new Tile({y:8, x:10, height: 0, type: "water"}),
    new Tile({y:8, x:11, height: 0, type: "water"}),
    new Tile({y:8, x:12, height: 0, type: "water"}),
    new Tile({y:8, x:13, height: 0, type: "water"}),
    new Tile({y:8, x:14, height: 1}),
    new Tile({y:8, x:15, height: 2}),
    new Tile({y:8, x:16, height: 2}),
    new Tile({y:8, x:17, height: 2}),
    new Tile({y:8, x:18, height: 2}),
    new Tile({y:8, x:19, height: 2})
  ],
  [
    new Tile({y:9, x:0, height: 2}),
    new Tile({y:9, x:1, height: 2}),
    new Tile({y:9, x:2, height: 2}),
    new Tile({y:9, x:3, height: 2}),
    new Tile({y:9, x:4, height: 1}),
    new Tile({y:9, x:5, height: 0, type: "water"}),
    new Tile({y:9, x:6, height: 0, type: "water"}),
    new Tile({y:9, x:7, height: 0, type: "water"}),
    new Tile({y:9, x:8, height: 0, type: "water"}),
    new Tile({y:9, x:9, height: 0, type: "water"}),
    new Tile({y:9, x:10, height: 0, type: "water"}),
    new Tile({y:9, x:11, height: 0, type: "water"}),
    new Tile({y:9, x:12, height: 0, type: "water"}),
    new Tile({y:9, x:13, height: 0, type: "water"}),
    new Tile({y:9, x:14, height: 1}),
    new Tile({y:9, x:15, height: 2}),
    new Tile({y:9, x:16, height: 2}),
    new Tile({y:9, x:17, height: 2}),
    new Tile({y:9, x:18, height: 2}),
    new Tile({y:9, x:19, height: 2})
  ],
  [
    new Tile({y:10, x:0, height: 2}),
    new Tile({y:10, x:1, height: 2}),
    new Tile({y:10, x:2, height: 2}),
    new Tile({y:10, x:3, height: 2}),
    new Tile({y:10, x:4, height: 2}),
    new Tile({y:10, x:5, height: 1}),
    new Tile({y:10, x:6, height: 0, type: "water"}),
    new Tile({y:10, x:7, height: 0, type: "water"}),
    new Tile({y:10, x:8, height: 0, type: "water"}),
    new Tile({y:10, x:9, height: 0, type: "water"}),
    new Tile({y:10, x:10, height: 0, type: "water"}),
    new Tile({y:10, x:11, height: 0, type: "water"}),
    new Tile({y:10, x:12, height: 0, type: "water"}),
    new Tile({y:10, x:13, height: 1}),
    new Tile({y:10, x:14, height: 2}),
    new Tile({y:10, x:15, height: 2}),
    new Tile({y:10, x:16, height: 2}),
    new Tile({y:10, x:17, height: 2}),
    new Tile({y:10, x:18, height: 2}),
    new Tile({y:10, x:19, height: 2})
  ],
  [
    new Tile({y:11, x:0, height: 2}),
    new Tile({y:11, x:1, height: 2}),
    new Tile({y:11, x:2, height: 2}),
    new Tile({y:11, x:3, height: 2}),
    new Tile({y:11, x:4, height: 2}),
    new Tile({y:11, x:5, height: 1}),
    new Tile({y:11, x:6, height: 1}),
    new Tile({y:11, x:7, height: 1}),
    new Tile({y:11, x:8, height: 0, type: "water"}),
    new Tile({y:11, x:9, height: 0, type: "water"}),
    new Tile({y:11, x:10, height: 0, type: "water"}),
    new Tile({y:11, x:11, height: 1}),
    new Tile({y:11, x:12, height: 1}),
    new Tile({y:11, x:13, height: 2}),
    new Tile({y:11, x:14, height: 2}),
    new Tile({y:11, x:15, height: 2}),
    new Tile({y:11, x:16, height: 2}),
    new Tile({y:11, x:17, height: 2}),
    new Tile({y:11, x:18, height: 2}),
    new Tile({y:11, x:19, height: 2})
  ],
  [
    new Tile({y:12, x:0, height: 2}),
    new Tile({y:12, x:1, height: 2}),
    new Tile({y:12, x:2, height: 2}),
    new Tile({y:12, x:3, height: 2}),
    new Tile({y:12, x:4, height: 2}),
    new Tile({y:12, x:5, height: 2}),
    new Tile({y:12, x:6, height: 2}),
    new Tile({y:12, x:7, height: 1}),
    new Tile({y:12, x:8, height: 0, type: "water"}),
    new Tile({y:12, x:9, height: 1}),
    new Tile({y:12, x:10, height: 0, type: "water"}),
    new Tile({y:12, x:11, height: 1}),
    new Tile({y:12, x:12, height: 2}),
    new Tile({y:12, x:13, height: 2}),
    new Tile({y:12, x:14, height: 2}),
    new Tile({y:12, x:15, height: 2}),
    new Tile({y:12, x:16, height: 2}),
    new Tile({y:12, x:17, height: 2}),
    new Tile({y:12, x:18, height: 2}),
    new Tile({y:12, x:19, height: 2})
  ],
  [
    new Tile({y:13, x:0, height: 2}),
    new Tile({y:13, x:1, height: 2}),
    new Tile({y:13, x:2, height: 2}),
    new Tile({y:13, x:3, height: 2}),
    new Tile({y:13, x:4, height: 2}),
    new Tile({y:13, x:5, height: 2}),
    new Tile({y:13, x:6, height: 2}),
    new Tile({y:13, x:7, height: 1}),
    new Tile({y:13, x:8, height: 0, type: "water"}),
    new Tile({y:13, x:9, height: 1}),
    new Tile({y:13, x:10, height: 1}),
    new Tile({y:13, x:11, height: 1}),
    new Tile({y:13, x:12, height: 2}),
    new Tile({y:13, x:13, height: 2}),
    new Tile({y:13, x:14, height: 2}),
    new Tile({y:13, x:15, height: 2}),
    new Tile({y:13, x:16, height: 2}),
    new Tile({y:13, x:17, height: 2}),
    new Tile({y:13, x:18, height: 2}),
    new Tile({y:13, x:19, height: 2})
  ],
  [
    new Tile({y:14, x:0, height: 2}),
    new Tile({y:14, x:1, height: 2}),
    new Tile({y:14, x:2, height: 2}),
    new Tile({y:14, x:3, height: 2}),
    new Tile({y:14, x:4, height: 2}),
    new Tile({y:14, x:5, height: 2}),
    new Tile({y:14, x:6, height: 2}),
    new Tile({y:14, x:7, height: 1}),
    new Tile({y:14, x:8, height: 1}),
    new Tile({y:14, x:9, height: 1}),
    new Tile({y:14, x:10, height: 2}),
    new Tile({y:14, x:11, height: 2}),
    new Tile({y:14, x:12, height: 2}),
    new Tile({y:14, x:13, height: 2}),
    new Tile({y:14, x:14, height: 2}),
    new Tile({y:14, x:15, height: 2}),
    new Tile({y:14, x:16, height: 2}),
    new Tile({y:14, x:17, height: 2}),
    new Tile({y:14, x:18, height: 2}),
    new Tile({y:14, x:19, height: 2})
  ],
  [
    new Tile({y:15, x:0, height: 2}),
    new Tile({y:15, x:1, height: 2}),
    new Tile({y:15, x:2, height: 2}),
    new Tile({y:15, x:3, height: 2}),
    new Tile({y:15, x:4, height: 2}),
    new Tile({y:15, x:5, height: 2}),
    new Tile({y:15, x:6, height: 2}),
    new Tile({y:15, x:7, height: 2}),
    new Tile({y:15, x:8, height: 2}),
    new Tile({y:15, x:9, height: 2}),
    new Tile({y:15, x:10, height: 2}),
    new Tile({y:15, x:11, height: 2}),
    new Tile({y:15, x:12, height: 2}),
    new Tile({y:15, x:13, height: 2}),
    new Tile({y:15, x:14, height: 2}),
    new Tile({y:15, x:15, height: 2}),
    new Tile({y:15, x:16, height: 2}),
    new Tile({y:15, x:17, height: 2}),
    new Tile({y:15, x:18, height: 2}),
    new Tile({y:15, x:19, height: 2})
  ],
  [
    new Tile({y:16, x:0, height: 2}),
    new Tile({y:16, x:1, height: 2}),
    new Tile({y:16, x:2, height: 2}),
    new Tile({y:16, x:3, height: 2}),
    new Tile({y:16, x:4, height: 2}),
    new Tile({y:16, x:5, height: 2}),
    new Tile({y:16, x:6, height: 2}),
    new Tile({y:16, x:7, height: 2}),
    new Tile({y:16, x:8, height: 2}),
    new Tile({y:16, x:9, height: 2}),
    new Tile({y:16, x:10, height: 2}),
    new Tile({y:16, x:11, height: 2}),
    new Tile({y:16, x:12, height: 2}),
    new Tile({y:16, x:13, height: 2}),
    new Tile({y:16, x:14, height: 2}),
    new Tile({y:16, x:15, height: 2}),
    new Tile({y:16, x:16, height: 2}),
    new Tile({y:16, x:17, height: 2}),
    new Tile({y:16, x:18, height: 2}),
    new Tile({y:16, x:19, height: 2})
  ],
  [
    new Tile({y:17, x:0, height: 2}),
    new Tile({y:17, x:1, height: 2}),
    new Tile({y:17, x:2, height: 2}),
    new Tile({y:17, x:3, height: 2}),
    new Tile({y:17, x:4, height: 2}),
    new Tile({y:17, x:5, height: 2}),
    new Tile({y:17, x:6, height: 2}),
    new Tile({y:17, x:7, height: 2}),
    new Tile({y:17, x:8, height: 2}),
    new Tile({y:17, x:9, height: 2}),
    new Tile({y:17, x:10, height: 2}),
    new Tile({y:17, x:11, height: 2}),
    new Tile({y:17, x:12, height: 2}),
    new Tile({y:17, x:13, height: 2}),
    new Tile({y:17, x:14, height: 2}),
    new Tile({y:17, x:15, height: 2}),
    new Tile({y:17, x:16, height: 2}),
    new Tile({y:17, x:17, height: 2}),
    new Tile({y:17, x:18, height: 2}),
    new Tile({y:17, x:19, height: 2})
  ],
  [
    new Tile({y:18, x:0, height: 2}),
    new Tile({y:18, x:1, height: 2}),
    new Tile({y:18, x:2, height: 2}),
    new Tile({y:18, x:3, height: 2}),
    new Tile({y:18, x:4, height: 2}),
    new Tile({y:18, x:5, height: 2}),
    new Tile({y:18, x:6, height: 2}),
    new Tile({y:18, x:7, height: 2}),
    new Tile({y:18, x:8, height: 2}),
    new Tile({y:18, x:9, height: 2}),
    new Tile({y:18, x:10, height: 2}),
    new Tile({y:18, x:11, height: 2}),
    new Tile({y:18, x:12, height: 2}),
    new Tile({y:18, x:13, height: 2}),
    new Tile({y:18, x:14, height: 2}),
    new Tile({y:18, x:15, height: 2}),
    new Tile({y:18, x:16, height: 2}),
    new Tile({y:18, x:17, height: 2}),
    new Tile({y:18, x:18, height: 2}),
    new Tile({y:18, x:19, height: 2})
  ],
  [
    new Tile({y:19, x:0, height: 2}),
    new Tile({y:19, x:1, height: 2}),
    new Tile({y:19, x:2, height: 2}),
    new Tile({y:19, x:3, height: 2}),
    new Tile({y:19, x:4, height: 2}),
    new Tile({y:19, x:5, height: 2}),
    new Tile({y:19, x:6, height: 2}),
    new Tile({y:19, x:7, height: 2}),
    new Tile({y:19, x:8, height: 2}),
    new Tile({y:19, x:9, height: 2}),
    new Tile({y:19, x:10, height: 2}),
    new Tile({y:19, x:11, height: 2}),
    new Tile({y:19, x:12, height: 2}),
    new Tile({y:19, x:13, height: 2}),
    new Tile({y:19, x:14, height: 2}),
    new Tile({y:19, x:15, height: 2}),
    new Tile({y:19, x:16, height: 2}),
    new Tile({y:19, x:17, height: 2}),
    new Tile({y:19, x:18, height: 2}),
    new Tile({y:19, x:19, height: 2})
  ],
],
}

const MAP1 = 
[
  [
    new Tile({y:0, x:0}),
    new Tile({y:0, x:1}),
    new Tile({y:0, x:2}),
    new Tile({y:0, x:3, height: 3, type: "rock"}),
    new Tile({y:0, x:4, height: 3, type: "rock"}),
    new Tile({y:0, x:5, height: 3, type: "rock"}),
    new Tile({y:0, x:6, height: 3, type: "rock"}),
    new Tile({y:0, x:7}),
    new Tile({y:0, x:8}),
    new Tile({y:0, x:9})
  ],
  [
    new Tile({y:1, x:0}),
    new Tile({y:1, x:1}),
    new Tile({y:1, x:2}),
    new Tile({y:1, x:3, height: 3, type: "rock"}),
    new Tile({y:1, x:4, height: 2, type: "rock"}),
    new Tile({y:1, x:5, height: 2, type: "rock"}),
    new Tile({y:1, x:6, height: 3, type: "rock"}),
    new Tile({y:1, x:7}),
    new Tile({y:1, x:8}),
    new Tile({y:1, x:9})
  ],
  [
    new Tile({y:2, x:0}),
    new Tile({y:2, x:1}),
    new Tile({y:2, x:2}),
    new Tile({y:2, x:3, height: 2, type: "rock"}),
    new Tile({y:2, x:4}),
    new Tile({y:2, x:5}),
    new Tile({y:2, x:6, height: 2, type: "rock"}),
    new Tile({y:2, x:7}),
    new Tile({y:2, x:8}),
    new Tile({y:2, x:9})
  ],[
    new Tile({y:3, x:0}),
    new Tile({y:3, x:1}),
    new Tile({y:3, x:2}),
    new Tile({y:3, x:3}),
    new Tile({y:3, x:4, height: 0}),
    new Tile({y:3, x:5}),
    new Tile({y:3, x:6}),
    new Tile({y:3, x:7}),
    new Tile({y:3, x:8}),
    new Tile({y:3, x:9})
  ],[
    new Tile({y:4, x:0}),
    new Tile({y:4, x:1}),
    new Tile({y:4, x:2}),
    new Tile({y:4, x:3}),
    new Tile({y:4, x:4, height: 0}),
    new Tile({y:4, x:5}),
    new Tile({y:4, x:6}),
    new Tile({y:4, x:7}),
    new Tile({y:4, x:8}),
    new Tile({y:4, x:9})
  ],[
    new Tile({y:5, x:0}),
    new Tile({y:5, x:1}),
    new Tile({y:5, x:2}),
    new Tile({y:5, x:3}),
    new Tile({y:5, x:4, height: 0}),
    new Tile({y:5, x:5, height: 0}),
    new Tile({y:5, x:6}),
    new Tile({y:5, x:7}),
    new Tile({y:5, x:8}),
    new Tile({y:5, x:9})
  ],[
    new Tile({y:6,x :0}),
    new Tile({y:6,x :1}),
    new Tile({y:6,x :2}),
    new Tile({y:6,x :3}),
    new Tile({y:6,x :4, height: 0}),
    new Tile({y:6,x :5, height: 0}),
    new Tile({y:6,x :6, height: 0}),
    new Tile({y:6,x :7, height: 0}),
    new Tile({y:6,x :8}),
    new Tile({y:6,x :9})
  ],[
    new Tile({y:7, x:0}),
    new Tile({y:7, x:1}),
    new Tile({y:7, x:2}),
    new Tile({y:7, x:3}),
    new Tile({y:7, x:4, height: 0}),
    new Tile({y:7, x:5, height: 0}),
    new Tile({y:7, x:6}),
    new Tile({y:7, x:7}),
    new Tile({y:7, x:8}),
    new Tile({y:7, x:9})
  ],[
    new Tile({y:8, x:0}),
    new Tile({y:8, x:1}),
    new Tile({y:8, x:2}),
    new Tile({y:8, x:3, height: 0}),
    new Tile({y:8, x:4, height: 0}),
    new Tile({y:8, x:5}),
    new Tile({y:8, x:6}),
    new Tile({y:8, x:7}),
    new Tile({y:8, x:8}),
    new Tile({y:8, x:9})
  ],
  [
    new Tile({y:9, x:0}),
    new Tile({y:9, x:1}),
    new Tile({y:9, x:2}),
    new Tile({y:9, x:3, height: 1}),
    new Tile({y:9, x:4}),
    new Tile({y:9, x:5}),
    new Tile({y:9, x:6}),
    new Tile({y:9, x:7}),
    new Tile({y:9, x:8}),
    new Tile({y:9, x:9})
  ],
  [
    new Tile({y:10, x:0}),
    new Tile({y:10, x:1}),
    new Tile({y:10, x:2}),
    new Tile({y:10, x:3, height: 1}),
    new Tile({y:10, x:4}),
    new Tile({y:10, x:5}),
    new Tile({y:10, x:6}),
    new Tile({y:10, x:7}),
    new Tile({y:10, x:8}),
    new Tile({y:10, x:9})
  ],
  [
    new Tile({y:11, x:0}),
    new Tile({y:11, x:1}),
    new Tile({y:11, x:2}),
    new Tile({y:11, x:3}),
    new Tile({y:11, x:4}),
    new Tile({y:11, x:5}),
    new Tile({y:11, x:6}),
    new Tile({y:11, x:7}),
    new Tile({y:11, x:8}),
    new Tile({y:11, x:9})
  ],
  [
    new Tile({y:12, x:0}),
    new Tile({y:12, x:1}),
    new Tile({y:12, x:2}),
    new Tile({y:12, x:3, height: 0}),
    new Tile({y:12, x:4}),
    new Tile({y:12, x:5}),
    new Tile({y:12, x:6}),
    new Tile({y:12, x:7}),
    new Tile({y:12, x:8}),
    new Tile({y:12, x:9})
  ],
  [
    new Tile({y:13, x:0}),
    new Tile({y:13, x:1}),
    new Tile({y:13, x:2}),
    new Tile({y:13, x:3, type: "grassland"}),
    new Tile({y:13, x:4}),
    new Tile({y:13, x:5}),
    new Tile({y:13, x:6}),
    new Tile({y:13, x:7}),
    new Tile({y:13, x:8}),
    new Tile({y:13, x:9})
  ],
];

const MAPTEMPLATE = 
[
  [
    new Tile({y:0, x:0}),
    new Tile({y:0, x:1}),
    new Tile({y:0, x:2}),
    new Tile({y:0, x:3}),
    new Tile({y:0, x:4}),
    new Tile({y:0, x:5}),
    new Tile({y:0, x:6}),
    new Tile({y:0, x:7}),
    new Tile({y:0, x:8}),
    new Tile({y:0, x:9}),
    new Tile({y:0, x:10}),
    new Tile({y:0, x:11}),
    new Tile({y:0, x:12}),
    new Tile({y:0, x:13}),
    new Tile({y:0, x:14}),
    new Tile({y:0, x:15}),
    new Tile({y:0, x:16}),
    new Tile({y:0, x:17}),
    new Tile({y:0, x:18}),
    new Tile({y:0, x:19})
  ],
  [
    new Tile({y:1, x:0}),
    new Tile({y:1, x:1}),
    new Tile({y:1, x:2}),
    new Tile({y:1, x:3}),
    new Tile({y:1, x:4}),
    new Tile({y:1, x:5}),
    new Tile({y:1, x:6}),
    new Tile({y:1, x:7}),
    new Tile({y:1, x:8}),
    new Tile({y:1, x:9}),
    new Tile({y:1, x:10}),
    new Tile({y:1, x:11}),
    new Tile({y:1, x:12}),
    new Tile({y:1, x:13}),
    new Tile({y:1, x:14}),
    new Tile({y:1, x:15}),
    new Tile({y:1, x:16}),
    new Tile({y:1, x:17}),
    new Tile({y:1, x:18}),
    new Tile({y:1, x:19})
  ],
  [
    new Tile({y:2, x:0}),
    new Tile({y:2, x:1}),
    new Tile({y:2, x:2}),
    new Tile({y:2, x:3}),
    new Tile({y:2, x:4}),
    new Tile({y:2, x:5}),
    new Tile({y:2, x:6}),
    new Tile({y:2, x:7}),
    new Tile({y:2, x:8}),
    new Tile({y:2, x:9}),
    new Tile({y:2, x:10}),
    new Tile({y:2, x:11}),
    new Tile({y:2, x:12}),
    new Tile({y:2, x:13}),
    new Tile({y:2, x:14}),
    new Tile({y:2, x:15}),
    new Tile({y:2, x:16}),
    new Tile({y:2, x:17}),
    new Tile({y:2, x:18}),
    new Tile({y:2, x:19})
  ],[
    new Tile({y:3, x:0}),
    new Tile({y:3, x:1}),
    new Tile({y:3, x:2}),
    new Tile({y:3, x:3}),
    new Tile({y:3, x:4}),
    new Tile({y:3, x:5}),
    new Tile({y:3, x:6}),
    new Tile({y:3, x:7}),
    new Tile({y:3, x:8}),
    new Tile({y:3, x:9}),
    new Tile({y:3, x:10}),
    new Tile({y:3, x:11}),
    new Tile({y:3, x:12}),
    new Tile({y:3, x:13}),
    new Tile({y:3, x:14}),
    new Tile({y:3, x:15}),
    new Tile({y:3, x:16}),
    new Tile({y:3, x:17}),
    new Tile({y:3, x:18}),
    new Tile({y:3, x:19})
  ],[
    new Tile({y:4, x:0}),
    new Tile({y:4, x:1}),
    new Tile({y:4, x:2}),
    new Tile({y:4, x:3}),
    new Tile({y:4, x:4}),
    new Tile({y:4, x:5}),
    new Tile({y:4, x:6}),
    new Tile({y:4, x:7}),
    new Tile({y:4, x:8}),
    new Tile({y:4, x:9}),
    new Tile({y:4, x:10}),
    new Tile({y:4, x:11}),
    new Tile({y:4, x:12}),
    new Tile({y:4, x:13}),
    new Tile({y:4, x:14}),
    new Tile({y:4, x:15}),
    new Tile({y:4, x:16}),
    new Tile({y:4, x:17}),
    new Tile({y:4, x:18}),
    new Tile({y:4, x:19})
  ],[
    new Tile({y:5, x:0}),
    new Tile({y:5, x:1}),
    new Tile({y:5, x:2}),
    new Tile({y:5, x:3}),
    new Tile({y:5, x:4}),
    new Tile({y:5, x:5}),
    new Tile({y:5, x:6}),
    new Tile({y:5, x:7}),
    new Tile({y:5, x:8}),
    new Tile({y:5, x:9}),
    new Tile({y:5, x:10}),
    new Tile({y:5, x:11}),
    new Tile({y:5, x:12}),
    new Tile({y:5, x:13}),
    new Tile({y:5, x:14}),
    new Tile({y:5, x:15}),
    new Tile({y:5, x:16}),
    new Tile({y:5, x:17}),
    new Tile({y:5, x:18}),
    new Tile({y:5, x:19})
  ],[
    new Tile({y:6,x :0}),
    new Tile({y:6,x :1}),
    new Tile({y:6,x :2}),
    new Tile({y:6,x :3}),
    new Tile({y:6,x :4}),
    new Tile({y:6,x :5}),
    new Tile({y:6,x :6}),
    new Tile({y:6,x :7}),
    new Tile({y:6,x :8}),
    new Tile({y:6,x :9}),
    new Tile({y:6, x:10}),
    new Tile({y:6, x:11}),
    new Tile({y:6, x:12}),
    new Tile({y:6, x:13}),
    new Tile({y:6, x:14}),
    new Tile({y:6, x:15}),
    new Tile({y:6, x:16}),
    new Tile({y:6, x:17}),
    new Tile({y:6, x:18}),
    new Tile({y:6, x:19})
  ],[
    new Tile({y:7, x:0}),
    new Tile({y:7, x:1}),
    new Tile({y:7, x:2}),
    new Tile({y:7, x:3}),
    new Tile({y:7, x:4}),
    new Tile({y:7, x:5}),
    new Tile({y:7, x:6}),
    new Tile({y:7, x:7}),
    new Tile({y:7, x:8}),
    new Tile({y:7, x:9}),
    new Tile({y:7, x:10}),
    new Tile({y:7, x:11}),
    new Tile({y:7, x:12}),
    new Tile({y:7, x:13}),
    new Tile({y:7, x:14}),
    new Tile({y:7, x:15}),
    new Tile({y:7, x:16}),
    new Tile({y:7, x:17}),
    new Tile({y:7, x:18}),
    new Tile({y:7, x:19})
  ],[
    new Tile({y:8, x:0}),
    new Tile({y:8, x:1}),
    new Tile({y:8, x:2}),
    new Tile({y:8, x:3}),
    new Tile({y:8, x:4}),
    new Tile({y:8, x:5}),
    new Tile({y:8, x:6}),
    new Tile({y:8, x:7}),
    new Tile({y:8, x:8}),
    new Tile({y:8, x:9}),
    new Tile({y:8, x:10}),
    new Tile({y:8, x:11}),
    new Tile({y:8, x:12}),
    new Tile({y:8, x:13}),
    new Tile({y:8, x:14}),
    new Tile({y:8, x:15}),
    new Tile({y:8, x:16}),
    new Tile({y:8, x:17}),
    new Tile({y:8, x:18}),
    new Tile({y:8, x:19})
  ],
  [
    new Tile({y:9, x:0}),
    new Tile({y:9, x:1}),
    new Tile({y:9, x:2}),
    new Tile({y:9, x:3}),
    new Tile({y:9, x:4}),
    new Tile({y:9, x:5}),
    new Tile({y:9, x:6}),
    new Tile({y:9, x:7}),
    new Tile({y:9, x:8}),
    new Tile({y:9, x:9}),
    new Tile({y:9, x:10}),
    new Tile({y:9, x:11}),
    new Tile({y:9, x:12}),
    new Tile({y:9, x:13}),
    new Tile({y:9, x:14}),
    new Tile({y:9, x:15}),
    new Tile({y:9, x:16}),
    new Tile({y:9, x:17}),
    new Tile({y:9, x:18}),
    new Tile({y:9, x:19})
  ],
  [
    new Tile({y:10, x:0}),
    new Tile({y:10, x:1}),
    new Tile({y:10, x:2}),
    new Tile({y:10, x:3}),
    new Tile({y:10, x:4}),
    new Tile({y:10, x:5}),
    new Tile({y:10, x:6}),
    new Tile({y:10, x:7}),
    new Tile({y:10, x:8}),
    new Tile({y:10, x:9}),
    new Tile({y:10, x:10}),
    new Tile({y:10, x:11}),
    new Tile({y:10, x:12}),
    new Tile({y:10, x:13}),
    new Tile({y:10, x:14}),
    new Tile({y:10, x:15}),
    new Tile({y:10, x:16}),
    new Tile({y:10, x:17}),
    new Tile({y:10, x:18}),
    new Tile({y:10, x:19})
  ],
  [
    new Tile({y:11, x:0}),
    new Tile({y:11, x:1}),
    new Tile({y:11, x:2}),
    new Tile({y:11, x:3}),
    new Tile({y:11, x:4}),
    new Tile({y:11, x:5}),
    new Tile({y:11, x:6}),
    new Tile({y:11, x:7}),
    new Tile({y:11, x:8}),
    new Tile({y:11, x:9}),
    new Tile({y:11, x:10}),
    new Tile({y:11, x:11}),
    new Tile({y:11, x:12}),
    new Tile({y:11, x:13}),
    new Tile({y:11, x:14}),
    new Tile({y:11, x:15}),
    new Tile({y:11, x:16}),
    new Tile({y:11, x:17}),
    new Tile({y:11, x:18}),
    new Tile({y:11, x:19})
  ],
  [
    new Tile({y:12, x:0}),
    new Tile({y:12, x:1}),
    new Tile({y:12, x:2}),
    new Tile({y:12, x:3}),
    new Tile({y:12, x:4}),
    new Tile({y:12, x:5}),
    new Tile({y:12, x:6}),
    new Tile({y:12, x:7}),
    new Tile({y:12, x:8}),
    new Tile({y:12, x:9}),
    new Tile({y:12, x:10}),
    new Tile({y:12, x:11}),
    new Tile({y:12, x:12}),
    new Tile({y:12, x:13}),
    new Tile({y:12, x:14}),
    new Tile({y:12, x:15}),
    new Tile({y:12, x:16}),
    new Tile({y:12, x:17}),
    new Tile({y:12, x:18}),
    new Tile({y:12, x:19})
  ],
  [
    new Tile({y:13, x:0}),
    new Tile({y:13, x:1}),
    new Tile({y:13, x:2}),
    new Tile({y:13, x:3}),
    new Tile({y:13, x:4}),
    new Tile({y:13, x:5}),
    new Tile({y:13, x:6}),
    new Tile({y:13, x:7}),
    new Tile({y:13, x:8}),
    new Tile({y:13, x:9}),
    new Tile({y:13, x:10}),
    new Tile({y:13, x:11}),
    new Tile({y:13, x:12}),
    new Tile({y:13, x:13}),
    new Tile({y:13, x:14}),
    new Tile({y:13, x:15}),
    new Tile({y:13, x:16}),
    new Tile({y:13, x:17}),
    new Tile({y:13, x:18}),
    new Tile({y:13, x:19})
  ],
  [
    new Tile({y:14, x:0}),
    new Tile({y:14, x:1}),
    new Tile({y:14, x:2}),
    new Tile({y:14, x:3}),
    new Tile({y:14, x:4}),
    new Tile({y:14, x:5}),
    new Tile({y:14, x:6}),
    new Tile({y:14, x:7}),
    new Tile({y:14, x:8}),
    new Tile({y:14, x:9}),
    new Tile({y:14, x:10}),
    new Tile({y:14, x:11}),
    new Tile({y:14, x:12}),
    new Tile({y:14, x:13}),
    new Tile({y:14, x:14}),
    new Tile({y:14, x:15}),
    new Tile({y:14, x:16}),
    new Tile({y:14, x:17}),
    new Tile({y:14, x:18}),
    new Tile({y:14, x:19})
  ],
  [
    new Tile({y:15, x:0}),
    new Tile({y:15, x:1}),
    new Tile({y:15, x:2}),
    new Tile({y:15, x:3}),
    new Tile({y:15, x:4}),
    new Tile({y:15, x:5}),
    new Tile({y:15, x:6}),
    new Tile({y:15, x:7}),
    new Tile({y:15, x:8}),
    new Tile({y:15, x:9}),
    new Tile({y:15, x:10}),
    new Tile({y:15, x:11}),
    new Tile({y:15, x:12}),
    new Tile({y:15, x:13}),
    new Tile({y:15, x:14}),
    new Tile({y:15, x:15}),
    new Tile({y:15, x:16}),
    new Tile({y:15, x:17}),
    new Tile({y:15, x:18}),
    new Tile({y:15, x:19})
  ],
  [
    new Tile({y:16, x:0}),
    new Tile({y:16, x:1}),
    new Tile({y:16, x:2}),
    new Tile({y:16, x:3}),
    new Tile({y:16, x:4}),
    new Tile({y:16, x:5}),
    new Tile({y:16, x:6}),
    new Tile({y:16, x:7}),
    new Tile({y:16, x:8}),
    new Tile({y:16, x:9}),
    new Tile({y:16, x:10}),
    new Tile({y:16, x:11}),
    new Tile({y:16, x:12}),
    new Tile({y:16, x:13}),
    new Tile({y:16, x:14}),
    new Tile({y:16, x:15}),
    new Tile({y:16, x:16}),
    new Tile({y:16, x:17}),
    new Tile({y:16, x:18}),
    new Tile({y:16, x:19})
  ],
  [
    new Tile({y:17, x:0}),
    new Tile({y:17, x:1}),
    new Tile({y:17, x:2}),
    new Tile({y:17, x:3}),
    new Tile({y:17, x:4}),
    new Tile({y:17, x:5}),
    new Tile({y:17, x:6}),
    new Tile({y:17, x:7}),
    new Tile({y:17, x:8}),
    new Tile({y:17, x:9}),
    new Tile({y:17, x:10}),
    new Tile({y:17, x:11}),
    new Tile({y:17, x:12}),
    new Tile({y:17, x:13}),
    new Tile({y:17, x:14}),
    new Tile({y:17, x:15}),
    new Tile({y:17, x:16}),
    new Tile({y:17, x:17}),
    new Tile({y:17, x:18}),
    new Tile({y:17, x:19})
  ],
  [
    new Tile({y:18, x:0}),
    new Tile({y:18, x:1}),
    new Tile({y:18, x:2}),
    new Tile({y:18, x:3}),
    new Tile({y:18, x:4}),
    new Tile({y:18, x:5}),
    new Tile({y:18, x:6}),
    new Tile({y:18, x:7}),
    new Tile({y:18, x:8}),
    new Tile({y:18, x:9}),
    new Tile({y:18, x:10}),
    new Tile({y:18, x:11}),
    new Tile({y:18, x:12}),
    new Tile({y:18, x:13}),
    new Tile({y:18, x:14}),
    new Tile({y:18, x:15}),
    new Tile({y:18, x:16}),
    new Tile({y:18, x:17}),
    new Tile({y:18, x:18}),
    new Tile({y:18, x:19})
  ],
  [
    new Tile({y:19, x:0}),
    new Tile({y:19, x:1}),
    new Tile({y:19, x:2}),
    new Tile({y:19, x:3}),
    new Tile({y:19, x:4}),
    new Tile({y:19, x:5}),
    new Tile({y:19, x:6}),
    new Tile({y:19, x:7}),
    new Tile({y:19, x:8}),
    new Tile({y:19, x:9}),
    new Tile({y:19, x:10}),
    new Tile({y:19, x:11}),
    new Tile({y:19, x:12}),
    new Tile({y:19, x:13}),
    new Tile({y:19, x:14}),
    new Tile({y:19, x:15}),
    new Tile({y:19, x:16}),
    new Tile({y:19, x:17}),
    new Tile({y:19, x:18}),
    new Tile({y:19, x:19})
  ],
];